---

- name: Ensure the venv suffix is set
  set_fact:
    diagrams_venv_suffix: "{{ diagrams_version }}"
  when: diagrams_venv_suffix is not defined
        or not diagrams_venv_suffix

- name: Ensure the Diagrams install directory exists
  file:
    path: "{{ diagrams_install_dir }}"
    state: directory

- name: Ensure Python 3 interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ diagrams_python3_path }}"

- name: Ensure Diagrams is installed in a virtual environment
  pip:
    name: diagrams
    version: "{{ diagrams_version }}"
    state: present
    virtualenv: "{{ diagrams_install_dir }}/{{ diagrams_venv_name }}-{{ diagrams_venv_suffix }}"
    virtualenv_command: "{{ diagrams_python3_path }} -m venv"
    virtualenv_site_packages: "{{ diagrams_venv_site_packages | default(False) }}"

- name: Ensure the originally configured Python interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ diagrams_ansible_python_interpreter }}"
  when: diagrams_ansible_python_interpreter is defined

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ diagrams_install_dir }}/{{ diagrams_venv_name }}-{{ diagrams_venv_suffix }}"
    dest: "{{ diagrams_install_dir }}/{{ diagrams_venv_name }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ diagrams_install_dir }}/{{ diagrams_venv_name }}-{{ diagrams_venv_suffix }}/bin/venv"
    mode: 0755
