---

- import_tasks: pre-checks-os.yml

- include_tasks: "{{ ansible_os_family | lower }}/install-os-dependencies.yml"
  when: diagrams_install_os_dependencies is defined
        and diagrams_install_os_dependencies

- import_tasks: pre-checks-environment.yml

- import_tasks: get-version.yml
  when: diagrams_version is not defined
        or not diagrams_version

- import_tasks: install-diagrams.yml

- import_tasks: post-checks-environment.yml
