---
- name: Converge
  hosts: all
  become: true
  vars:
    diagrams_install_os_dependencies: true
    diagrams_install_dir: /opt/diagrams/bin
    diagrams_current_dirname: current
  roles:
    - role: xanmanning.diagrams
