---

- name: Ensure graphviz, Python 3 and Python Pip is installed (YUM)
  yum:
    name:
      - graphviz
      - python3
      - python3-pip
      - python3-setuptools
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Ensure graphviz, Python 3 and Python Pip is installed (DNF)
  dnf:
    name:
      - graphviz
      - python3
      - python3-pip
      - python3-setuptools
    state: present
  when: ansible_pkg_mgr == "dnf"
